#! /bin/bash

if [[ $# < 1 ]]
  then
        echo -e "Не указаны параметры запуска.\nget-torrent-id <Торрент файл .torrent> [Произвольное имя]\n"
        exit
  fi

if [[ -e "$1" ]]
  then
        Id=$(transmission-show "$1" | grep Hash | awk '{print $2}')
        Name=$(transmission-show "$1" | grep Name | head -n 1 | awk '{print $2}')
        if [[ $2 != "" ]]
          then
                Name="$2"
          fi
        echo "#EXTINF:-1,$Name"
        echo "http://192.168.1.2:8000/infohash/$Id/0/stream.mp4"
  else
        echo "Торрент файл не существует."
  fi
